---

- name: Configure Hashicorp Repository
  ansible.builtin.deb822_repository:
    name: hashicorp
    types: deb
    uris: "{{ vagrant_repository_url }}"
    suites: '{{ ansible_distribution_release }}'
    components: main
    architectures: amd64
    signed_by: "{{ vagrant_repository_gpg_key }}"
    state: present

- name: Update Repositories
  ansible.builtin.apt:
    update_cache: true

- name: "Install Vagrant"
  ansible.builtin.apt:
    name: vagrant
    state: present
