---

- name: "Add Hashicorp Repository"
  block:

    - name: "Add Repository Key"
      ansible.builtin.get_url:
        url: "{{ vagrant_apt_repokey_url }}"
        dest: "{{ vagrant_apt_repokey_keyringfile }}"

    - name: "Add repository into sources list"
      ansible.builtin.apt_repository:
        repo: "{{ vagrant_apt_repo_url }}"
        state: present
        filename: hashicorp

- name: "Install Vagrant"
  ansible.builtin.apt:
    name: vagrant
    state: latest
    update_cache: yes
